CUBRID/cubrid-testcases

sql/conf/daily_regression_test_ha_repl.conf

1. add sql/conf/daily_regression_test_ha_repl.conf 
since there are 7290 cases, I only make 62 cases skip according regression test

[CUBRIDQA-4] add exclude list for ha_repl test

---

sql/_27_banana_qa/issue_5765_timezone_support/_08_current_date_function/_02_functions/cases/_13_datediff.sql

eg:
x1=xxxx-08-31 xx:xx:xx
current_datetime=xxxx-09-01 xx:xx:xx
x3=xxxx-11-01 xx:xx:xx
month(@x3)-month(@x1)=3
x1=xxxx-11-30 xx:xx:xx
current_datetime=xxxx-12-01 xx:xx:xx
x3=xxxx-02-01 xx:xx:xx
month(@x3)-month(@x1)=-9

[CUBRIDQA-12] modify cases,add new result value

---

sql/_17_sql_extension2/_02_full_test/_18_system_parameters/_02_string_max_size_bytes/cases/string_max_size_bytes_001.sql

[CUBRIDQA-12] add order by to group_concat function

---

sql/_13_issues/_12_1h/answers/bug_bts_6853.answer
sql/_23_apricot_qa/_02_performance/_02_function_based_index/answers/function_based_index_function_DAY.answer
sql/_23_apricot_qa/_02_performance/_02_function_based_index/answers/function_based_index_function_DAYOFYEAR.answer
sql/_23_apricot_qa/_02_performance/_02_function_based_index/answers/function_based_index_function_MONTH.answer
sql/_23_apricot_qa/_02_performance/_02_function_based_index/answers/function_based_index_function_QUARTER.answer
sql/_23_apricot_qa/_02_performance/_02_function_based_index/answers/function_based_index_function_YEAR.answer
sql/_23_apricot_qa/_02_performance/_02_function_based_index/answers/function_based_index_function_dayofweek.answer
sql/_23_apricot_qa/_02_performance/_02_function_based_index/answers/function_based_index_function_weekday.answer
sql/_27_banana_qa/issue_5765_timezone_support/_01_table_operations/_04_select/answers/_08_index_dt.answer
sql/_27_banana_qa/issue_5765_timezone_support/_01_table_operations/_04_select/answers/_08_index_dt.answer_cci
sql/_27_banana_qa/issue_5765_timezone_support/_01_table_operations/_04_select/answers/_08_index_ts.answer
sql/_27_banana_qa/issue_5765_timezone_support/_01_table_operations/_04_select/answers/_08_index_ts.answer_cci

http://jira.cubrid.org/browse/CBRD-20825

[CBRD-20825]revise required, update answer files.

---

sql/_13_issues/_17_1h/answers/cbrd_20912.answer
sql/_13_issues/_17_1h/cases/cbrd_20912.sql

Add test case for memory leak of index loose scan fix.
http://jira.cubrid.org/browse/CBRD-20912

[CBRD-20912] Add test case for memory leak of index loose scan fix

---

sql/_13_issues/_17_1h/answers/cbrd_20910.answer
sql/_13_issues/_17_1h/cases/cbrd_20910.sql

Add test case for the fix of reset compressed clear.
http://jira.cubrid.org/browse/CBRD-20910

[CBRD-20910] Add test case for the fix of reset compressed clear

---

sql/_13_issues/_17_1h/answers/cbrd_20936.answer
sql/_13_issues/_17_1h/cases/cbrd_20936.sql

Add test case for the fix of memory leak in MRO.
http://jira.cubrid.org/browse/CBRD-20936

[CBRD-20936] Add test case for the fix of memory leak in MRO

---

sql/_13_issues/_13_1h/answers/bug_bts_10470.answer_cci

Please refer to http://jira.cubrid.org/browse/CBRD-20953 and https://github.com/CUBRID/cubrid/pull/512 to review.
Thank you.

[CBRD-20953]revise required, query plan changed because of the fix on 'show create view'.

---

sql/_13_issues/_17_1h/answers/cbrd_20857.answer

Please refer to http://jira.cubrid.org/browse/CBRD-20865 and https://github.com/CUBRID/cubrid/pull/527 .

[CBRD-20865]revise required, update answer for the fix on CTE attributes printing.

---

sql/_13_issues/_17_1h/answers/cbrd_20949.answer
sql/_13_issues/_17_1h/cases/cbrd_20949.sql

Add test case for the fix of memory leak in MRO.
http://jira.cubrid.org/browse/CBRD-20949

[CBRD-20949] Add test case for the fix of memory leak in MRO

---

sql/_13_issues/_17_1h/answers/cbrd_20953.answer
sql/_13_issues/_17_1h/cases/cbrd_20953.sql

http://jira.cubrid.org/browse/CBRD-20953

[CBRD-20953]add test case for bug in 'shwo create view' when 'plus_as_concat=no'.

---

sql/_13_issues/_17_1h/answers/cbrd_20865.answer
sql/_13_issues/_17_1h/cases/cbrd_20865.sql

http://jira.cubrid.org/browse/CBRD-20865
add case to test trace info of cte query

[CBRD-20865] add case to test trace info of cte query

---

sql/_13_issues/_17_1h/answers/cbrd_20974.answer
sql/_13_issues/_17_1h/cases/cbrd_20974.sql

http://jira.cubrid.org/browse/CBRD-20974

[CBRD-20974]add test case for server crash in show index.

---

sql/_13_issues/_17_1h/answers/cbrd_21067.answer
sql/_13_issues/_17_1h/cases/cbrd_21067.sql

Add test case for the fix of disable multi range optimization instead return error when regu variable didn't match.
http://jira.cubrid.org/browse/CBRD-21067

[CBRD-21067] Add test case for the fix of disable multi range optimization instead return error when regu variable didn't match

---

sql/config/daily_regression_test_exclude_list_ha_repl.conf

refer to http://jira.cubrid.org/browse/CUBRIDSUS-9241

[CUBRIDSUS-9241] ha don't support nested insert

---

sql/config/daily_regression_test_exclude_list_ha_repl.conf

refer to http://jira.cubrid.org/browse/CBRD-21284

[CBRD-21284] exclude it,it has been marked 'not a bug'

---

sql/config/daily_regression_test_exclude_list_ha_repl.conf

CUBRIDSUS-9241: ha don't support nested insert 
CBRD-21344 :defult expression

[CUBRIDSUS-9241][CBRD-21344] exlude them,nested insert and default expression"

---

sql/config/daily_regression_test_exclude_list_ha_repl.conf

refer to 
http://jira.cubrid.org/browse/CBRD-21344

[CBRD-21344] master and slave has little difference for default expression.exclude it

---

sql/_30_banana_pie_qa/issue_20399_default_ext/answers/cte_with_default_clause.answer
sql/_30_banana_pie_qa/issue_20399_default_ext/cases/cte_with_default_clause.sql

to stable sql case for default clause in cte

[CBRD-20399] stable case for default clause in cte

---

sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_8.4.1_D_patch
sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_8.4.3_D_patch
sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_8.4.4_D_patch
sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_9.2.0_D_patch
sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_9.3.0_D_patch

refer to CUBRIDQA-181
sql answers has changed. so update patch files.

[CUBRIDQA-181] sql answers changed,so update patch files

---

sql/_28_features_930/issue_13613_hint_index_ss/answers/_01_plain_table.answer

refer to #205
CTP tools changed,
also modify release/10.0 answers

[CUBRIDQA-153]update answer for the fix of CTP to print CTE query plan.

---

isolation/_01_ReadCommitted/issues/_17_2h/answer/bug_bts_5221.answer
isolation/_01_ReadCommitted/issues/_17_2h/bug_bts_5221.ctl

Automate this test case as an isolation test case.
* Remove from cubrid-testcases-private/manually repository:
https://github.com/CUBRID/cubrid-testcases-private/pull/341
* Add to cubrid-testcases/isolation repository:
https://github.com/CUBRID/cubrid-testcases/pull/234

[CUBRIDQA-258]Automate manually/shell/1hour/bug_bts_5221 as an isolation scenario.

---

sql/_27_banana_qa/issue_12401_DML_Natural_Join/cases/02_natural_join_003.sql

http://jira.cubrid.org/browse/CUBRIDQA-375
Add ORDER BY to make test case stable.

[CUBRIDQA-375] stabilize sql case via ORDER BY

---

isolation/_04_RepeatableRead_ReadCommitted/index_column/common_index/aggregate/answer/insert_select_01_5.answer

Forgot to update answer file when refine the test case(https://github.com/CUBRID/cubrid-testcases/pull/264).

[CUBRIDQA-20]update answer for refined test case.

---

sql/_27_banana_qa/issue_11089_percentile_disc/_01_aggregate_function/cases/_08_expression.sql

http://jira.cubrid.org/browse/CUBRIDQA-399

[CUBRIDQA-399]fix ambiguous queries.

---

sql/_27_banana_qa/issue_5765_timezone_support/_11_partition/cases/69_field.sql

fix a slip of https://github.com/CUBRID/cubrid-testcases/pull/281

[CUBRIDQA-451]remove test code and add drop table.

---

sql/_14_mysql_compatibility_2/_04_table_related/_02_alter_change_column/_16_shared_attribute/cases/name.master.slave1.diff_1
sql/_14_mysql_compatibility_2/_04_table_related/_02_alter_change_column/_16_shared_attribute/cases/name_order.master.slave1.diff_1

[CUBRIDQA-445] update diff_1

---

sql/_31_cherry/issue_21522_json/answers/json_where_clause_complex.answer

http://jira.cubrid.org/browse/CBRD-21697
https://github.com/CUBRID/cubrid-testcases/pull/317

[CBRD-21697]update answer for sql updated in #317.

---

sql/_31_cherry/issue_21522_json/answers/json_i18n.answer

http://jira.cubrid.org/browse/CBRD-21691

[CBRD-21691]update answer for the fix of json comparison.

---

sql/_31_cherry/issue_21522_json/answers/json_002.answer
sql/_31_cherry/issue_21522_json/cases/json_002.sql

http://jira.cubrid.org/browse/CBRD-21660

[CBRD-21660]Remove comment for server crash in db_json_get_type_as_str fixed.

---

sql/_13_issues/_18_1h/answers/cbrd_21567.answer
sql/_13_issues/_18_1h/cases/cbrd_21567.sql

http://jira.cubrid.org/browse/CBRD-21567

[CBRD-21567]add test case for copy comments for CREATE TABLE LIKE

---

sql/_13_issues/_14_1h/answers/bug_bts_11912.answer
sql/_13_issues/_14_1h/cases/bug_bts_11912.sql

http://jira.cubrid.org/browse/CBRD-21808

[CBRD-21808]revise wrong query.

---

sql/_31_cherry/issue_21522_json/answers/json_varchar_cast.answer

http://jira.cubrid.org/browse/CBRD-21672

[CBRD-21672]revise answer for CUBRID supprot SQL/JSON path.

---

isolation/_01_ReadCommitted/issues/_18_1h/answer/cbrd_21900.answer
isolation/_01_ReadCommitted/issues/_18_1h/cbrd_21900.ctl

http://jira.cubrid.org/browse/CBRD-21900

[CBRD-21900]add test case for deadlock detection.

---

sql/_31_cherry/issue_21522_json/answers/json_misc.answer
sql/_31_cherry/issue_21522_json/cases/json_misc.sql

http://jira.cubrid.org/browse/CBRD-21945
sql/_31_cherry/issue_21522_json/cases/json_misc.sql(line 19 and line 20) already contains the issued queries in CBRD-21945, so just add a select query to verify the results.

[CBRD-21945]add a select query to verify the result of json_insert().

---

isolation/_01_ReadCommitted/catalog/answer/db_index_01.answer
isolation/_01_ReadCommitted/catalog/answer/db_index_02.answer
isolation/_01_ReadCommitted/catalog/answer/db_index_03.answer
isolation/_01_ReadCommitted/catalog/answer/db_index_04.answer
isolation/_01_ReadCommitted/catalog/answer/db_index_05.answer
isolation/_01_ReadCommitted/catalog/answer/db_index_06.answer
isolation/_02_RepeatableRead/catalog/answer/db_index_01.answer
isolation/_02_RepeatableRead/catalog/answer/db_index_02.answer
isolation/_02_RepeatableRead/catalog/answer/db_index_03.answer
isolation/_02_RepeatableRead/catalog/answer/db_index_04.answer
isolation/_02_RepeatableRead/catalog/answer/db_index_05.answer
isolation/_02_RepeatableRead/catalog/answer/db_index_06.answer
isolation/_02_RepeatableRead/index_column/common_index/basic_sql/answer/delete_select_04.answer
isolation/_02_RepeatableRead/index_column/common_index/basic_sql/answer/delete_select_09.answer
isolation/_04_RepeatableRead_ReadCommitted/dml_ddl/answer/createindex_01.answer
isolation/_04_RepeatableRead_ReadCommitted/dml_ddl/answer/createindex_02.answer
isolation/_05_ReadCommitted_RepeatableRead/dml_ddl/answer/createindex_01.answer
isolation/_05_ReadCommitted_RepeatableRead/dml_ddl/answer/createindex_02.answer
isolation/_05_ReadCommitted_RepeatableRead/index_column/common_index/basic_sql/answer/delete_select_01_ext.answer
isolation/_05_ReadCommitted_RepeatableRead/index_column/common_index/basic_sql/answer/delete_select_02_ext.answer
isolation/_05_ReadCommitted_RepeatableRead/index_column/common_index/basic_sql/answer/delete_select_04.answer
isolation/_05_ReadCommitted_RepeatableRead/index_column/common_index/basic_sql/answer/delete_select_09.answer
isolation/_05_ReadCommitted_RepeatableRead/primary_key_column/basic_sql/answer/delete_select_02_ext.answer
medium/_02_xtests/answers/cat1.answer
medium/_02_xtests/answers/cat11.answer
medium/_02_xtests/answers/cat8.answer

http://jira.cubrid.org/browse/CBRD-22195
Update answer files for isolation test and medium test.

[CBRD-22195]db_index schema changed, update answer files.

---

isolation/_01_ReadCommitted/authorization/changing_owner/answer/changing_owner_05.answer
isolation/_01_ReadCommitted/authorization/method/answer/changing_owner_02.answer
isolation/_01_ReadCommitted/authorization/method/answer/changing_owner_03.answer

http://jira.cubrid.org/browse/CBRD-22015?focusedCommentId=4751867&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4751867

[CBRD-22015]update answers for the change of authorization behavior.

---

sql/_27_banana_qa/issue_5765_timezone_support/_01_table_operations/_02_alter/answers/_01_alter_add_hard_default_yes_dtltz.answer_win
sql/_27_banana_qa/issue_5765_timezone_support/_01_table_operations/_02_alter/answers/_01_alter_add_hard_default_yes_dttz.answer_win
sql/_27_banana_qa/issue_5765_timezone_support/_01_table_operations/_02_alter/answers/_01_alter_add_hard_default_yes_tsltz.answer_win
sql/_27_banana_qa/issue_5765_timezone_support/_01_table_operations/_02_alter/answers/_01_alter_add_hard_default_yes_tstz.answer_win

http://jira.cubrid.org/browse/CBRD-22255
Update Windows answers.

[CBRD-22255] show index statement has Visible column

---

sql/_31_cherry/issue_21672_json_functions/answers/json_array_append_in_dml.answer

http://jira.cubrid.org/browse/CBRD-22298
https://github.com/CUBRID/cubrid/pull/1195

[CBRD-22298]update answer for change of JSON_ARRAY_INSERT.

---

sql/_13_issues/_15_1h/answers/bug_bts_14846.answer
sql/_31_cherry/issue_22162_more_json_functions/cases/json_bigint.sql

http://jira.cubrid.org/browse/CBRD-21755

[CBRD-21755]add JSON type into _db_data_type table.

---

sql/_14_mysql_compatibility_2/_11_logical_operations/answers/002_plans.answer
sql/_23_apricot_qa/_01_sql_extension3/_02_new_sql_types/_01_enum/answers/_20_enum_operators01.answer
sql/_23_apricot_qa/_02_performance/_02_function_based_index/answers/function_based_index_function_IF.answer

http://jira.cubrid.org/browse/CBRD-22454

[CBRD-22454]revise answers for change of cast.

---

isolation/_01_ReadCommitted/cbrd_21506/create_ddl/answer/create_01.answer
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/answer/create_02.answer
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/answer/create_03.answer
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/answer/create_04.answer
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/answer/create_06.answer
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/answer/create_07.answer
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/answer/create_08.answer
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/answer/create_10.answer
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/answer/create_11.answer
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/answer/create_14.answer
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/answer/show_001.answer
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/create_01.ctl
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/create_02.ctl
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/create_03.ctl
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/create_04.ctl
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/create_06.ctl
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/create_07.ctl
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/create_08.ctl
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/create_10.ctl
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/create_11.ctl
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/create_14.ctl
isolation/_01_ReadCommitted/cbrd_21506/create_ddl/show_001.ctl

test point:
Use CTL tool:
(1)  add/drop/rename column while  loading index
(2). change column data type/name while  loading index

[CUBRIDQA-807][CBRD-21506] add test cases:alter column while loading index

---

sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_select_2.answer

http://jira.cubrid.org/browse/CBRD-22442
https://github.com/CUBRID/cubrid/pull/1310

[CBRD-22442]Revise answer for fix of printing json table column type.

---

sql/_13_issues/_18_2h/answers/cbrd_22419.answer_cci

refer to https://github.com/CUBRID/cubrid-testcases/pull/516

[CBRD-22419]add sql_by_cci answer for cbrd_22419.sql

---

sql/_13_issues/_18_2h/answers/cbrd_22418.answer
sql/_13_issues/_18_2h/answers/cbrd_22418_2.answer
sql/_13_issues/_18_2h/cases/cbrd_22418.sql
sql/_13_issues/_18_2h/cases/cbrd_22418_2.sql

refer to http://jira.cubrid.org/browse/CBRD-22418

[CBRD-22418] add test cases: null value with online index

---

sql/_31_cherry/issue_21506_online_index/answers/unique_index_03.answer
sql/_31_cherry/issue_21506_online_index/cases/cbrd_22427.sql

cbrd_22427.sql : add order by column
unique_index_03.answer : time zone is inconsistent with daily qa test env, update answer.

[CUBRIDQA-12]add order by clause and update answer

---

sql/_31_cherry/issue_21506_online_index/answers/cbrd_22532.answer
sql/_31_cherry/issue_21506_online_index/cases/cbrd_22532.sql

http://jira.cubrid.org/browse/CBRD-22532

[CBRD-22532] create online index with UNDER class

---

sql/_31_cherry/issue_22162_more_json_functions/cases/json_double_arrow_operator.sql

http://jira.cubrid.org/browse/CBRD-22541

[CBRD-22541]check the data type of double_arrow_operator

---

sql/_23_apricot_qa/_02_performance/_02_function_based_index/answers/function_based_index_coverage_003.answer

It is a revise required case of http://jira.cubrid.org/browse/CBRD-22632

[CBRD-22632]revise for better handling of the index_status

---

sql/_31_cherry/issue_22162_more_json_functions/answers/cbrd_22461.answer
sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_create_table_as.answer
sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_create_table_as.answer_cci
sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_examples_2.answer
sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_group_concat.answer
sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_multi.answer

http://jira.cubrid.org/browse/CBRD-22540

[CBRD-22540]revise for fix of json_path wildcards.

---

sql/_31_cherry/issue_22202_invisible_index/answers/invisible_index_rebuild.answer
sql/_31_cherry/issue_22202_invisible_index/cases/invisible_index_rebuild.sql

http://jira.cubrid.org/browse/CBRD-22619

[CBRD-22619]add test case for rebuild invisible index.

---

sql/_31_cherry/issue_22162_more_json_functions/answers/cbrd_22698.answer
sql/_31_cherry/issue_22162_more_json_functions/cases/cbrd_22698.sql

http://jira.cubrid.org/browse/CBRD-22698

[CBRD-22698]add test case for json_table.

---

sql/_31_cherry/issue_22162_more_json_functions/answers/cbrd_22461.answer
sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_create_table_as.answer
sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_create_table_as.answer_cci
sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_examples_2.answer
sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_group_concat.answer
sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_multi.answer
sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_select_2.answer

http://jira.cubrid.org/browse/CBRD-22723
https://github.com/CUBRID/cubrid/pull/1462
revise answer for fix of json_path

[CBRD-22723]revise answer for fix of json_path

---

sql/_31_cherry/issue_21672_json_functions/answers/json_functions_misc.answer

https://github.com/CUBRID/cubrid/commit/b4cfdebc436599c86b83f81d777e5497fd0ceb83

[CBRD-22784] Modified error message

---

sql/_31_cherry/issue_22054_on_update/answers/trigger_002.answer_win

Corresponding to the case:https://github.com/CUBRID/cubrid-testcases/pull/644

[CBRD-22054]  update windows answer for modified test case.

---

sql/_31_cherry/issue_22161_CTE_extensions/_03_insert/cases/inst_num.sql

Stabilize the case to add control conditions

[CUBRIDQA-12]Add constraints.

---

sql/_31_cherry/issue_22162_more_json_functions/answers/cbrd_22703.answer
sql/_31_cherry/issue_22162_more_json_functions/cases/cbrd_22703.sql

http://jira.cubrid.org/browse/CBRD-22703

[CBRD-22703]add test case for slow query on json_table.

---

sql/_31_cherry/issue_22162_more_json_functions/answers/json_functions_with_host_variable_1.answer
sql/_31_cherry/issue_22162_more_json_functions/cases/json_functions_with_host_variable_1.sql

http://jira.cubrid.org/browse/CBRD-22672

[CBRD-22672]add test case for fix of behavior using host variable.

---

sql/_14_mysql_compatibility_2/_04_table_related/_02_alter_change_column/_16_shared_attribute/cases/name.master.slave1.diff_1
sql/_14_mysql_compatibility_2/_04_table_related/_02_alter_change_column/_16_shared_attribute/cases/name_order.master.slave1.diff_1

refer to https://github.com/CUBRID/cubrid-testcases/pull/500

[CUBRIDQA-776] update diff_1 file

---

sql/_27_banana_qa/issue_5765_timezone_support/_00_dev_cases/_02_operator/_06_cast_op_with_tz/cases/1055.sql
sql/_28_features_930/issue_13613_hint_index_ss/answers/_01_plain_table.answer
sql/_28_features_930/issue_13613_hint_index_ss/answers/_01_plain_table.answer_cci

http://jira.cubrid.org/browse/CBRD-21953

[CBRD-21953]Add order by and correct the answer

---

sql/_14_mysql_compatibility_2/_04_table_related/_02_alter_change_column/_16_shared_attribute/cases/name.master.slave1.diff_1

refer to http://qahome.cubrid.org/qaresult/showFailResult.nhn?m=showFailVerifyItem&statid=3721&srctb=ha_repl_main&failType=ha_repl

[CUBRIDQA-961] update diff_1 files

---

isolation/_01_ReadCommitted/issues/_19_2h/answer/cbrd_22972.answer
isolation/_01_ReadCommitted/issues/_19_2h/cbrd_22972.ctl

http://jira.cubrid.org/browse/CBRD-22972

[CBRD-22972]add test case for the issue when instant locking is stopped

---

isolation/_01_ReadCommitted/issues/_18_1h/answer/cbrd_21900.answer

http://jira.cubrid.org/browse/CBRD-23185

[CBRD-23185]revise answer due to new lock mode.

---

sql/_31_cherry/issue_21672_json_functions/answers/json_path_1.answer
sql/_31_cherry/issue_21672_json_functions/answers/json_path_1.answer_cci

http://jira.cubrid.org/browse/CBRD-22546

[CBRD-22546]Modify the answer

---

sql/_13_issues/_14_2h/cases/bug_bts_12326.sql

[CUBRIDQA-12]add order by

---

sql/_06_manipulation/_01_select/_003_subquery/cases/1015.sql

http://jira.cubrid.org/browse/CBRD-23396

[CBRD-23396]add holdcas on

---

sql/_19_apricot/_10_enum_type/answers/index_002.answer
sql/_19_apricot/_10_enum_type/cases/index_002.sql
sql/_23_apricot_qa/_03_i18n/ja_JP/_04_using_index/cases/1001.sql
sql/_23_apricot_qa/_03_i18n/km_KH/_04_using_index/cases/1001.sql
sql/_24_aprium_qa/_01_i18n/issue_8700_enum/cases/index_002.sql
sql/_24_aprium_qa/_03_other/issue_6091_orderbynum/answers/_03_mro_ranges_orderbynum.answer
sql/_24_aprium_qa/_03_other/issue_6091_orderbynum/cases/_03_mro_ranges_orderbynum.sql

When run test case: https://github.com/CUBRID/cubrid-testcases-private/tree/develop/shell_ext/general/cbrd_22705/cases
There are some failures caused by unstable sql test cases

[CUBRIDQA-911] make cases stable

---

sql/_31_cherry/issue_22162_more_json_functions/answers/cbrd_22679.answer
sql/_31_cherry/issue_22162_more_json_functions/answers/cbrd_22679.answer_cci
sql/_31_cherry/issue_22162_more_json_functions/cases/cbrd_22679.sql

http://jira.cubrid.org/browse/CBRD-22679

[CBRD-22679]add test case for function-based index with JSON functions

---

sql/_31_cherry/issue_22054_on_update/answers/update_001.answer
sql/_31_cherry/issue_22054_on_update/cases/update_001.sql

http://jira.cubrid.org/browse/CBRD-23460

[CBRD-23460]make the case stable

---

sql/_13_issues/_14_2h/answers/bug_bts_6705.answer
sql/_13_issues/_14_2h/cases/bug_bts_6705.sql

[CUBRIDQA-12]add ordered

---

sql/_10_connect_by/_09_hq_range_partition/cases/_002_performance_partition.sql

http://jira.cubrid.org/browse/CUBRIDQA-989

[CUBRIDQA-989]modify unstable testcase

---

sql/_24_aprium_qa/_03_other/issue_7441_MRO/answers/_03_mro_ranges.answer
sql/_24_aprium_qa/_03_other/issue_7441_MRO/cases/_03_mro_ranges.sql

http://jira.cubrid.org/browse/CUBRIDQA-996

[CUBRIDQA-996]add order by

---

sql/_18_index_enhancement_qa/_02_full_test/_06_optimizing_limit/cases/_18_between_stress.sql

Try to make status due to missing plan.

[CUBRIDQA-20] try to make status due to missing plan

---

sql/_01_object/_02_class/_001_basic/cases/cubridsus-1502.sql
sql/_01_object/_03_virtual_class/_007_updatable_view/cases/1009.sql

http://jira.cubrid.org/browse/CUBRIDQA-1030

[CUBRIDQA-1030]format the queries to stablilize the results.

---

sql/_13_issues/_12_2h/cases/bug_bts_7382.sql

http://jira.cubrid.org/browse/CUBRIDQA-1030
http://qahome.cubrid.org/qaresult/showfile.nhn?treeId=&level=&summaryName=&catPath=&name=&m=showCaseFile&statid=238299&itemid=2165494&tc=sql_by_cci&buildId=10.2.0.8797-d56a158&filePath=sql%2F_13_issues%2F_12_2h%2Fcases%2Fbug_bts_7382.sql&isNew=&isSuccessFul=false

[CUBRIDQA-1030]format query

---

sql/_32_damson/cbrd_22783_REGEXP_functions/answers/REGEXP_COUNT.answer
sql/_32_damson/cbrd_22783_REGEXP_functions/answers/REGEXP_REPLACE.answer
sql/_32_damson/cbrd_22783_REGEXP_functions/cases/REGEXP_COUNT.sql
sql/_32_damson/cbrd_22783_REGEXP_functions/cases/REGEXP_INSTR.sql
sql/_32_damson/cbrd_22783_REGEXP_functions/cases/REGEXP_LIKE.sql
sql/_32_damson/cbrd_22783_REGEXP_functions/cases/REGEXP_REPLACE.sql
sql/_32_damson/cbrd_22783_REGEXP_functions/cases/REGEXP_SUBSTR.sql

http://jira.cubrid.org/browse/CBRD-22783

[CBRD-22783] make the case stable.

---

sql/_32_damson/cbrd_22783_REGEXP_functions/answers/REGEXP_LIKE.answer

http://jira.cubrid.org/browse/CBRD-23085

[CBRD-23085] modified answer for fixed case

---

sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_ext_8.4.1_D_patch
sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_ext_8.4.3_D_patch
sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_ext_8.4.4_D_patch
sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_ext_9.2.0_D_patch
sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_ext_9.3.0_D_patch

Refer to http://jira.cubrid.org/browse/CBRD-23611, #811 
Backported for #811.
Modified the patch file related to CBRD-23611.
Modified file list
- sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_8.4.1_D_patch
- sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_8.4.3_D_patch
- sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_8.4.4_D_patch
- sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_9.2.0_D_patch
- sql/config/daily_regression_test_exclude_list_compatibility/patch_files/jdbc_sql_9.3.0_D_patch

[CBRD-23611] (Backport) Modified the patch file (relate to padding)

---

sql/_13_issues/_20_2h/answers/cbrd_23623.answer
sql/_13_issues/_20_2h/cases/cbrd_23623.sql

http://jira.cubrid.org/browse/CBRD-23623

[CBRD-23623] add new case for this issue

---

isolation/_01_ReadCommitted/index_column/function_index/up_up_code_cov_01.ctl

http://jira.cubrid.org/browse/CBRD-23679

[CBRD-23679] revise isolation test case

---

isolation/_01_ReadCommitted/index_column/common_index/basic_sql/answer/insert_delete_01.answer
isolation/_01_ReadCommitted/index_column/common_index/basic_sql/answer/insert_insert_16.answer
isolation/_01_ReadCommitted/index_column/common_index/basic_sql/answer/insert_select_03.answer
isolation/_01_ReadCommitted/index_column/filter_index/basic_sql/answer/insert_delete_01.answer
isolation/_01_ReadCommitted/index_column/filter_index/basic_sql/answer/insert_select_03.answer
isolation/_01_ReadCommitted/index_column/multi_index/basic_sql/answer/delete_insert_21.answer
isolation/_01_ReadCommitted/primary_key_column/basic_sql/answer/insert_insert_15.answer
isolation/_01_ReadCommitted/primary_key_column/basic_sql/answer/insert_insert_16.answer
isolation/_02_RepeatableRead/index_column/multi_index/basic_sql/answer/delete_insert_03.answer
isolation/_04_RepeatableRead_ReadCommitted/index_column/common_index/basic_sql/answer/insert_insert_16.answer
isolation/_05_ReadCommitted_RepeatableRead/index_column/multi_index/basic_sql/answer/delete_insert_03.answer

http://jira.cubrid.org/browse/CBRD-23649

[CBRD-23649] revise isolation test case for this issue

---

sql/_23_apricot_qa/_01_sql_extension3/_05_analytic_functions/_04_max/cases/max_group_by.master.slave1.diff_1

Refer to http://jira.cubrid.org/browse/CBRD-23708

[CBRD-23708] Modified the patch file for CBRD-23708 (in ha_repl test)

---

isolation/_01_ReadCommitted/catalog/answer/db_class_02.answer
isolation/_01_ReadCommitted/catalog/answer/db_partition_02.answer
isolation/_02_RepeatableRead/catalog/answer/db_class_02.answer
isolation/_02_RepeatableRead/catalog/answer/db_partition_02.answer

http://jira.cubrid.org/browse/CBRD-23708

[CBRD_23708] Revise the isolaion testcases by reuseoid

---

isolation/_01_ReadCommitted/function/string_function/answer/update_delete_01.answer
isolation/_01_ReadCommitted/index_column/function_index/answer/delete_update_02.answer

refer to http://jira.cubrid.org/browse/CBRD-23731

[CBRD-23731] revise the isolation testcases by trailing space

---

sql/_24_aprium_qa/_03_other/issue_6091_orderbynum/answers/_05_mro_partition_orderbynum.answer
sql/_24_aprium_qa/_03_other/issue_7441_MRO/answers/_05_mro_partition.answer
sql/_31_cherry/issue_22162_more_json_functions/answers/json_table_group_concat.answer

Refer to http://jira.cubrid.org/browse/CBRD-23732

[CBRD-23732] Modified the test cases for CBRD-23732

---

sql/_13_issues/_12_2h/answers/bug_bts_9935_03.answer

http://jira.cubrid.org/browse/CBRD-23732

[CBRD-23732]revised answer for CBRD-23732.

---

medium/_02_xtests/answers/7105.answer
medium/_02_xtests/answers/7210.answer
medium/_02_xtests/answers/cat1.answer
medium/_02_xtests/answers/cat10.answer
medium/_02_xtests/answers/cat13.answer
medium/_02_xtests/answers/cat6.answer
medium/_02_xtests/answers/cat8.answer
medium/_02_xtests/answers/unique2.answer
medium/_02_xtests/answers/unique4.answer

http://jira.cubrid.org/browse/CBRD-23608

[CBRD-23608]revised medium answer for tde.

---

sql/_13_issues/_20_2h/answers/cbrd_23665.answer
sql/_13_issues/_20_2h/cases/cbrd_23665.sql

http://jira.cubrid.org/browse/CBRD-23665

[CBRD-23665] Add sql testcase for hash list scan

---

isolation/_01_ReadCommitted/index_column/function_index/answer/delete_delete_02.answer

refer to http://jira.cubrid.org/browse/CBRD-23731

[CBRD-23731] revise isolation testcase for this issue

---

isolation/_01_ReadCommitted/catalog/answer/db_class_06.answer
isolation/_02_RepeatableRead/catalog/answer/db_class_06.answer
isolation/_02_RepeatableRead/issues/_15_1h/answer/bug_bts_14847.answer
isolation/_04_RepeatableRead_ReadCommitted/dml_ddl/answer/altertable_02.answer
isolation/_04_RepeatableRead_ReadCommitted/dml_ddl/answer/createtable_02.answer
isolation/_04_RepeatableRead_ReadCommitted/dml_ddl/answer/createtable_03.answer
isolation/_05_ReadCommitted_RepeatableRead/dml_ddl/answer/altertable_02.answer
isolation/_05_ReadCommitted_RepeatableRead/dml_ddl/answer/createtable_02.answer
isolation/_05_ReadCommitted_RepeatableRead/dml_ddl/answer/createtable_03.answer

refer to http://jira.cubrid.org/browse/CBRD-23608

[CBRD-23608] revise isolation testcases for TDE

---

sql/_23_apricot_qa/_02_performance/_01_filtered_index/cases/filtered_index_basicfunction_Create_003.sql

http://jira.cubrid.org/browse/CBRD-23731

[CBRD-23731]revised typo.

---

sql/_23_apricot_qa/_03_i18n/ko_KR/_18_system_table/answers/08_db_class.answer_cci
sql/_23_apricot_qa/_03_i18n/ko_KR/_18_system_table/answers/09_db_vclass.answer_cci
sql/_23_apricot_qa/_03_i18n/ko_KR/_18_system_table/answers/_03_db_class.answer_cci

http://jira.cubrid.org/browse/CBRD-23608

[CBRD-23608] revised cci answer for tde.

---

sql/_13_issues/_20_2h/answers/cbrd_23749.answer
sql/_13_issues/_20_2h/answers/cbrd_23749.answer_cci
sql/_13_issues/_20_2h/cases/cbrd_23749.sql

http://jira.cubrid.org/browse/CBRD-23749

[CBRD-23749] Add new testcase for Hierarchical Queries Hash List Scan.
